serde/variant: restrict constructor template
Only enable the constructor taking universal references for values that
can be used to construct the underlying variant type. Previously, the
constructor template was considered during overload resolution for any
type, leading to hard-to-debug template instantiation errors when
unrelated types couldn't actually construct the variant.

The fix adds `std::is_constructible_v<type, T>` to the requires clause
to prevent template instantiation for incompatible types.

Example error before fix:

```
bazel-out/k8-fastbuild/bin/src/v/serde/_virtual_includes/variant/serde/rw/variant.h:64:9: error: no matching constructor for initialization of 'std::variant<pattern_type, pattern_match>'
   64 |       : type(std::forward<T>(t)){};
      |         ^    ~~~~~~~~~~~~~~~~~~
bazel-out/k8-fastbuild/bin/src/v/json/_virtual_includes/json/json/json.h:100:28: note: in instantiation of function template specialization 'serde::variant<security::pattern_type, security::resource_pattern_filter::pattern_match>::variant<const seastar::basic_sstring<char, unsigned int, 15> &>' requested here
  100 |         rjson_serialize(w, e);
      |                            ^
bazel-out/k8-fastbuild/bin/src/v/compat/_virtual_includes/compat/compat/json.h:390:5: note: in instantiation of function template specialization 'json::rjson_serialize<rapidjson::GenericStringBuffer<rapidjson::UTF8<>, json::throwing_allocator>, seastar::basic_sstring<char, unsigned int, 15>, std::allocator<seastar::basic_sstring<char, unsigned int, 15>>>' requested here
  390 |     rjson_serialize(w, b.mount_paths);
      |     ^
```