[CORE-13995] iceberg/filesystem_catalog: check version hint before writing table
In DatalakeCustomPartitioningTest.test_spec_evolution_rpcn the datalake
verifier complained that it was missing data.

```
AssertionError: Topic foo validation errors: ['Offset from Iceberg table 2325 is greater than next consumed offset 1042 for partition 4, most likely there is a gap in the table']
```

Upon further inspection, it seems to actually legitimately be missing data,
because it is using the filesystem catalog, which is unsafe.

To understand this, we can see that the translators are definitely processing
record batches in range [1042, 2287]:

```
TRACE 2025-10-15 01:42:04,643 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:444 - multiplexer finish complete: offset_range=[1013,1041], total_records=29, kafka_bytes=3451
TRACE 2025-10-15 01:42:04,712 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:130 - processing batch: offset_range=[1042,1042], records=1, raw_bytes=119, decompressed_bytes=119
TRACE 2025-10-15 01:42:04,759 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:364 - batch processing complete: last_offset=1042, writers_active=1
TRACE 2025-10-15 01:42:04,759 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:130 - processing batch: offset_range=[1043,1043], records=1, raw_bytes=119, decompressed_bytes=119
TRACE 2025-10-15 01:42:04,759 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:364 - batch processing complete: last_offset=1043, writers_active=1
TRACE 2025-10-15 01:42:04,759 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:130 - processing batch: offset_range=[1044,1044], records=1, raw_bytes=119, decompressed_bytes=119
TRACE 2025-10-15 01:42:04,759 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:364 - batch processing complete: last_offset=1044, writers_active=1
TRACE 2025-10-15 01:42:04,759 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:130 - processing batch: offset_range=[1045,1045], records=1, raw_bytes=119, decompressed_bytes=119
TRACE 2025-10-15 01:42:04,759 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:364 - batch processing complete: last_offset=1045, writers_active=1
TRACE 2025-10-15 01:42:04,759 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:130 - processing batch: offset_range=[1046,1046], records=1, raw_bytes=119, decompressed_bytes=119
TRACE 2025-10-15 01:42:04,759 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:364 - batch processing complete: last_offset=1046, writers_active=1
TRACE 2025-10-15 01:42:04,759 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:130 - processing batch: offset_range=[1047,1047], records=1, raw_bytes=119, decompressed_bytes=119
TRACE 2025-10-15 01:42:04,759 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:364 - batch processing complete: last_offset=1047, writers_active=1
TRACE 2025-10-15 01:42:04,759 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:130 - processing batch: offset_range=[1048,1048], records=1, raw_bytes=119, decompressed_bytes=119
...
TRACE 2025-10-15 01:42:10,778 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:130 - processing batch: offset_range=[2283,2283], records=1, raw_bytes=120, decompressed_bytes=120
TRACE 2025-10-15 01:42:10,778 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:364 - batch processing complete: last_offset=2283, writers_active=1
TRACE 2025-10-15 01:42:10,778 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:130 - processing batch: offset_range=[2284,2284], records=1, raw_bytes=120, decompressed_bytes=120
TRACE 2025-10-15 01:42:10,778 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:364 - batch processing complete: last_offset=2284, writers_active=1
TRACE 2025-10-15 01:42:10,778 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:130 - processing batch: offset_range=[2285,2285], records=1, raw_bytes=120, decompressed_bytes=120
TRACE 2025-10-15 01:42:10,778 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:364 - batch processing complete: last_offset=2285, writers_active=1
TRACE 2025-10-15 01:42:10,778 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:130 - processing batch: offset_range=[2286,2286], records=1, raw_bytes=120, decompressed_bytes=120
TRACE 2025-10-15 01:42:10,778 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:364 - batch processing complete: last_offset=2286, writers_active=1
TRACE 2025-10-15 01:42:10,778 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:130 - processing batch: offset_range=[2287,2287], records=1, raw_bytes=120, decompressed_bytes=120
TRACE 2025-10-15 01:42:10,778 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:364 - batch processing complete: last_offset=2287, writers_active=1
TRACE 2025-10-15 01:42:10,778 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:391 - starting multiplexer finish: writers=1, kafka_bytes_processed=148970
TRACE 2025-10-15 01:42:10,779 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:404 - writer finished: files_created=1)
TRACE 2025-10-15 01:42:10,779 [shard 5:data] datalake - {kafka/foo/4} - record_multiplexer.cc:444 - multiplexer finish complete: offset_range=[1042,2287], total_records=1246, kafka_bytes=148970
```

On the coordinator side, we see the files being added:

```
DEBUG 2025-10-15 01:42:10,923 [shard 7:main] datalake - coordinator.cc:557 - Sync add files requested {foo/4} (topic rev: 30): [1042, 2287], kafka_bytes: 148970 files: 1
...
DEBUG 2025-10-15 01:42:10,927 [shard 7:main] datalake - [{kafka_internal/datalake_coordinator/1} (datalake_coordinator_stm.snapshot)] - state_machine.cc:113 - Applying update_key::add_files from offset 17: {tp: {foo/4}, revision: 30, entries: [{start_offset: 1042, last_offset: 2287, files: [{remote_path: redpanda-iceberg-catalog/redpanda/foo/data/timestamp_hour=2025-10-15-01/4-e4113761-672a-4c87-b683-ac255fd22dd4.parquet, row_count: 1246, file_size_bytes: 42464, hour_deprecated: 0, table_schema_id: 0, partition_spec_id: 0}], dlq_files: [], kafka_bytes_processed: 148970}] (1 entries)}
...
DEBUG 2025-10-15 01:42:11,118 [shard 7:main] datalake - [{kafka_internal/datalake_coordinator/1} (datalake_coordinator_stm.snapshot)] - state_machine.cc:113 - Applying update_key::add_files from offset 18: {tp: {foo/4}, revision: 30, entries: [{start_offset: 2288, last_offset: 2324, files: [{remote_path: redpanda-iceberg-catalog/redpanda/foo/data/timestamp_hour=2025-10-15-01/4-62cd79cb-2cac-46fc-8d81-2b48e7c44761.parquet, row_count: 37, file_size_bytes: 2991, hour_deprecated: 0, table_schema_id: 0, partition_spec_id: 0}], dlq_files: [], kafka_bytes_processed: 4440}] (1 entries)}
...
DEBUG 2025-10-15 01:42:12,893 [shard 7:main] datalake - iceberg_file_committer.cc:345 - Adding 2 files to Iceberg table {ns: redpanda, table: foo}
INFO  2025-10-15 01:42:12,893 [shard 7:main] iceberg - merge_append_action.cc:173 - Building append update for 2 data files
...
INFO  2025-10-15 01:42:12,901 [shard 7:main] iceberg - merge_append_action.cc:425 - Considering 1 existing manifest files and 2 data files to merge
DEBUG 2025-10-15 01:42:12,901 [shard 7:main] iceberg - merge_append_action.cc:485 - Merging 0 manifest files and 2 added manifest entries
INFO  2025-10-15 01:42:12,901 [shard 7:main] iceberg - merge_append_action.cc:372 - Uploading manifest with 2 entries to abfss://panda-container-fe7e7294-a967-11f0-a3df-83d155232e47@cdtstrg473865226548.dfs.core.windows.net/redpanda-iceberg-catalog/redpanda/foo/metadata/f1c3dbd8-cc17-4d95-8439-00127c5fadb1-m0.avro
...
DEBUG 2025-10-15 01:42:12,995 [shard 7:main] cloud_io - [fiber66~0|1|30000ms] - remote.cc:1166 - Uploading iceberg::table_metadata to path "redpanda-iceberg-catalog/redpanda/foo/metadata/v2.metadata.json", length 2925
TRACE 2025-10-15 01:42:12,995 [shard 7:main] http - [/panda-container-fe7e7294-a967-11f0-a3df-83d155232e47/redpanda-iceberg-catalog/redpanda/foo/metadata/v2.metadata.json] - client.cc:125 - client.make_request PUT /panda-container-fe7e7294-a967-11f0-a3df-83d155232e47/redpanda-iceberg-catalog/redpanda/foo/metadata/v2.metadata.json HTTP/1.1
DEBUG 2025-10-15 01:42:12,995 [shard 7:main] http - [/panda-container-fe7e7294-a967-11f0-a3df-83d155232e47/redpanda-iceberg-catalog/redpanda/foo/metadata/v2.metadata.json] - client.cc:137 - reusing connection, age 0
TRACE 2025-10-15 01:42:12,995 [shard 7:main] http - /panda-container-fe7e7294-a967-11f0-a3df-83d155232e47/redpanda-iceberg-catalog/redpanda/foo/metadata/v2.metadata.json - client.cc:507 - request_stream.send_some 2925
TRACE 2025-10-15 01:42:13,057 [shard 7:main] http - /panda-container-fe7e7294-a967-11f0-a3df-83d155232e47/redpanda-iceberg-catalog/redpanda/foo/metadata/v2.metadata.json - client.cc:368 - chunk received, chunk length 398
...
DEBUG 2025-10-15 01:42:13,130 [shard 7:main] datalake - [{kafka_internal/datalake_coordinator/1} (datalake_coordinator_stm.snapshot)] - state_machine.cc:121 - Applying update_key::mark_files_committed from offset 19: {tp: {foo/4}, revision: 30, new_committed: 2324, kafka_bytes_processed: 153410}
```

The commit ends up in v2.metadata.json.

Concurrently, we see the following operation to update the schema coming in,
which also ends up rewriting v2.metadata.json.

```
DEBUG 2025-10-15 01:42:13,071 [shard 7:main] datalake - coordinator.cc:324 - sync_ensure_table_exists requested, topic: foo rev: 30
...
DEBUG 2025-10-15 01:42:13,131 [shard 7:main] cloud_io - [fiber75~0|1|30000ms] - remote.cc:1166 - Uploading iceberg::table_metadata to path "redpanda-iceberg-catalog/redpanda/foo/metadata/v2.metadata.json", length 2371
...
WARN  2025-10-15 01:42:13,230 [shard 7:main] iceberg - filesystem_catalog.cc:217 - Version hint file "redpanda-iceberg-catalog/redpanda/foo/metadata/version-hint.text" refers to version 2, expected 1
WARN  2025-10-15 01:42:13,230 [shard 7:main] datalake - catalog_schema_manager.cc:51 - Error while committing schema update to table {ns: redpanda, table: foo}: catalog::errc::unexpected_state
```

This unintentional overwrite of v2.metadata.json effectively removes the files
that we just committed.

One way to decrease (but not completely eliminate) the chance of this happening
is to check the version hint before writing metadata, rather than only doing
the check after. This commit makes this change.

A more robust solution would be to use atomic writes, but that is a much larger
project.

(cherry picked from commit 46e2728c9780efd4ccf4283d110c05945a5db57e)