rptest: use StrEnum for compatibility with older python
In newer versions of python using `class X(str, Enum)` resulted in errors like:

```
botocore.exceptions.InvalidS3AddressingStyleError: S3 addressing style S3AddressingStyle.PATH is invalid. Valid options are: 'auto', 'virtual', and 'path'
```

and

```
ptest.clients.rpk.RpkException: RpkException<command /var/lib/buildkite-agent/builds/buildkite-amd64-xfs-builders-i-0f522f278317d53c5-1/redpanda/redpanda/vbuild/redpanda_installs/ci/bin/rpk topic -X brokers=docker-rp-19:9092 produce --key don't -z CompressionTypes.NONE --delivery-timeout 5s ftest -f %v -X globals.request_timeout_overhead=5.5s -v returned 1, output: ; stderr: invalid compression codec "CompressionTypes.NONE"
; returncode: 1>
```

This keeps the behavior the same.

In addition, in a few places we switch to explicitly converting the enum
into a string using `.value`. This makes typecheckers happier.