rptest: switch duckdb to spark in dlq test
Our duckdb query service requires S3 (presumably it just needs more work
on our end):

```
AssertionError: DuckDBPy query service is implemented only for S3 credentials
```

Testing matrix is more uniform now.